# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a223e769b25a5cda798c6dca43c48210fc812df44bd059d3804a4c9bd21482620f1c9c8b119c4da81f9e3dad16ecd870b6e9674858a10fc2528a482314b6ffd3

test:
  secret_key_base: 30ba09f38cf8b80b8c4a41fab9be97cb6b63b0b4b8e641a12a1fc7bd9f30e1135fca7d30ca4b7d5f42bf1e16125a158dc35b710c3b15bacd12e00dc18eef643c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
